spring:
  application:
    name: pharmacy
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com.example.pharmacy: DEBUG
app:
  security:
    api-key-name: x-api-key
    api-key-value: your-secret-api-key
